version: '3'

services:
  postgres:
    image: postgres:15.4
    volumes:
      - ../postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ada-lovelace
      - POSTGRES_PASSWORD=cielo123
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=consumer
    ports:
      - 5432:5432
    networks:
      - postgre-network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}


networks:
  postgre-network:
    driver:
      bridge
