spring:
  application:
    name: consumer-for-sqs
  datasource:
    url: jdbc:postgresql://localhost:5432/consumer
    username: ada-lovelace
    password: cielo123
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    user: ada-lovelace
    password: cielo123
    url: jdbc:postgresql://localhost:5432/consumer
    enabled: false
    test-rollback-on-update: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


server:
  servlet:
    context-path: /api/feedback

aws:
  sns:
    default-group-id: 1
    topic-arn:
      elogios: arn:aws:sns:us-east-1:578310391489:bootcamp-desafio1-sns-topicoelogios.fifo
      sugestoes: arn:aws:sns:us-east-1:578310391489:bootcamp-desafio1-sns-topicosugestoes.fifo
      criticas: arn:aws:sns:us-east-1:578310391489:bootcamp-desafio1-sns-topicocriticas.fifo
  sqs:
    queue-url:
      elogios: https://sqs.us-east-1.amazonaws.com/578310391489/bootcamp-desafio1-sqs-elogios.fifo
      sugestoes: https://sqs.us-east-1.amazonaws.com/578310391489/bootcamp-desafio1-sqs-sugestoes.fifo
      criticas: https://sqs.us-east-1.amazonaws.com/578310391489/bootcamp-desafio1-sqs-criticas.fifo
