spring:
  application:
    name: consumer-for-sqs
  datasource:
    url: jdbc:postgresql://localhost:5432/consumer
    username: ada-lovelace
    password: cielo123
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  servlet:
    context-path: /api/feedback

aws:
  sns:
    default-group-id: 1
    topic-arn:
      elogios: arn:aws:sns:us-east-1:258160824945:bootcamp-desafio1-sns-topicoelogios.fifo
      sugestoes: arn:aws:sns:us-east-1:258160824945:bootcamp-desafio1-sns-topicosugestoes.fifo
      criticas: arn:aws:sns:us-east-1:258160824945:bootcamp-desafio1-sns-topicocriticas.fifo
